**Analisis e Sentimiento de Noticias para Prediccion del Mercado**

Objetivo: Consolidar 3 fuentes de noticias dispares en una unica serie temporal de 'sentimiento diario'

In [2]:
#Importamos las librerias

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re  # Para expresiones regulares (limpieza de texto)

#Librerías de NLP
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer

#Configuración
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (12, 8)

In [4]:
#Cargamos los datos
df_cnbc = pd.read_csv('cnbc_headlines.csv')
df_guardian = pd.read_csv('guardian_headlines.csv')
df_reuters = pd.read_csv('reuters_headlines.csv')

print(f'CNBC: {df_cnbc.shape}')
print(f'Guardian: {df_guardian.shape}')
print(f'Reuters: {df_reuters.shape}')

CNBC: (3080, 3)
Guardian: (17800, 2)
Reuters: (32770, 3)

In [5]:
df_cnbc.head()

,Headlines,Time,Description
0,Jim Cramer: A better way to invest in the Covi...,"7:51 PM ET Fri, 17 July 2020","""Mad Money"" host Jim Cramer recommended buying..."
1,Cramer's lightning round: I would own Teradyne,"7:33 PM ET Fri, 17 July 2020","""Mad Money"" host Jim Cramer rings the lightnin..."
2,NaN,NaN,NaN
3,"Cramer's week ahead: Big week for earnings, ev...","7:25 PM ET Fri, 17 July 2020","""We'll pay more for the earnings of the non-Co..."
4,IQ Capital CEO Keith Bliss says tech and healt...,"4:24 PM ET Fri, 17 July 2020","Keith Bliss, IQ Capital CEO, joins ""Closing Be..."

In [6]:
df_guardian.head()

        Time                                          Headlines
0  18-Jul-20   Johnson is asking Santa for a Christmas recovery
1  18-Jul-20  ‘I now fear the worst’: four grim tales of wor...
2  18-Jul-20  Five key areas Sunak must tackle to serve up e...
3  18-Jul-20  Covid-19 leaves firms ‘fatally ill-prepared’ f...
4  18-Jul-20  The Week in Patriarchy  \n\n\n  Bacardi's 'lad...

In [7]:
df_reuters.head()

,Headlines,Time,Description
0,TikTok considers London and other locations fo...,Jul 18 2020,TikTok has been in discussions with the UK gov...
1,Disney cuts ad spending on Facebook amid growi...,Jul 18 2020,Walt Disney has become the latest company to ...
2,Trail of missing Wirecard executive leads to B...,Jul 18 2020,Former Wirecard chief operating officer Jan M...
3,Twitter says attackers downloaded data from up...,Jul 18 2020,Twitter Inc said on Saturday that hackers were...
4,U.S. Republicans seek liability protections as...,Jul 17 2020,A battle in the U.S. Congress over a new coron...

Notemos que tenemos un problema importante, tenemos 3 formatos de fecha diferentes, asi que convertiremos los 3 formatos de fecha a uno solo.

Usaremos error='coerce' para manejar fallos de parseo, conviertiendolos a NaT (Not a Time) que luego eliminaremos

In [ ]:
#Reuters 
df_reuters['date'] = pd.to_datetime(
    df_reuters['Time'],
    format='%b %d %Y',
    errors= 'coerce'
)

#Guardian 
df_guardian['date'] = pd.to_datetime(
    df_guardian['Time'],
    format='%d-%b-%y',
    errors= 'coerce'
)
#CNBC 
date_regex= r'(\d{1,2}\w+ \d{4})'
df_cnbc['date_extrated']= df_cnbc['Time'].astype(str)